export const GARAGE_PART_CATALOG = [
  'Air Filter',
  'Cabin Filter',
  'Oil Filter',
  'Fuel Filter',
  'Transmission Filter',
  'Hydraulic Filter',
  'Breather Filter',
  'Spark Plug',
  'Glow Plug',
  'Ignition Coil',
  'Distributor Cap',
  'Rotor Arm',
  'HT Lead Set',
  'Battery Terminal',
  'Battery Clamp',
  'Battery 45Ah',
  'Battery 60Ah',
  'Battery 75Ah',
  'Alternator',
  'Starter Motor',
  'Starter Solenoid',
  'Drive Belt',
  'Fan Belt',
  'Timing Belt',
  'Timing Chain Kit',
  'Belt Tensioner',
  'Idler Pulley',
  'Water Pump',
  'Thermostat',
  'Radiator Cap',
  'Radiator Hose Upper',
  'Radiator Hose Lower',
  'Heater Hose',
  'Coolant Reservoir',
  'Coolant 5L',
  'Engine Oil 5W30',
  'Engine Oil 10W40',
  'Engine Oil 15W40',
  'ATF Transmission Fluid',
  'Gear Oil 75W90',
  'Brake Fluid DOT 4',
  'Power Steering Fluid',
  'Grease Cartridge',
  'Silicone Sealant',
  'Gasket Maker',
  'Engine Mount',
  'Gearbox Mount',
  'Suspension Bush',
  'Control Arm',
  'Lower Arm Bush',
  'Upper Arm Bush',
  'Ball Joint',
  'Tie Rod End',
  'Rack End',
  'Steering Rack Boot',
  'Wheel Bearing Front',
  'Wheel Bearing Rear',
  'Hub Assembly',
  'CV Joint Outer',
  'CV Joint Inner',
  'CV Boot Kit',
  'Drive Shaft',
  'Shock Absorber Front',
  'Shock Absorber Rear',
  'Strut Mount',
  'Coil Spring',
  'Leaf Spring Bush',
  'Stabilizer Link',
  'Sway Bar Bush',
  'Brake Pad Set Front',
  'Brake Pad Set Rear',
  'Brake Shoe Set',
  'Brake Disc Front',
  'Brake Disc Rear',
  'Brake Drum',
  'Brake Caliper',
  'Brake Master Cylinder',
  'Brake Wheel Cylinder',
  'Brake Booster',
  'Brake Hose',
  'ABS Sensor',
  'Clutch Plate',
  'Clutch Cover',
  'Release Bearing',
  'Clutch Kit',
  'Clutch Slave Cylinder',
  'Clutch Master Cylinder',
  'Flywheel',
  'Universal Joint',
  'Prop Shaft Center Bearing',
  'Differential Oil Seal',
  'Gear Lever Bush',
  'Fuel Pump',
  'Fuel Injector',
  'Injector Seal Kit',
  'Throttle Body',
  'Idle Control Valve',
  'MAP Sensor',
  'MAF Sensor',
  'Oxygen Sensor',
  'Knock Sensor',
  'Crank Sensor',
  'Cam Sensor',
  'Temperature Sensor',
  'Oil Pressure Switch',
  'Reverse Light Switch',
  'Fuse Assortment',
  'Relay 4 Pin',
  'Relay 5 Pin',
  'Headlight Bulb H4',
  'Headlight Bulb H7',
  'Indicator Bulb',
  'Brake Light Bulb',
  'Number Plate Bulb',
  'Wiper Blade 14 inch',
  'Wiper Blade 16 inch',
  'Wiper Blade 18 inch',
  'Wiper Blade 20 inch',
  'Wiper Motor',
  'Washer Pump',
  'Window Regulator',
  'Door Lock Actuator',
  'Door Handle',
  'Side Mirror',
  'Tail Light Assembly',
  'Headlight Assembly',
  'Bumper Clip',
  'Panel Clip',
  'Wheel Nut',
  'Wheel Stud',
  'Steel Rim 14 inch',
  'Tyre 175/70R13',
  'Tyre 185/65R14',
  'Tyre 195/65R15',
  'Tyre Valve',
  'Tubeless Repair Plug',
  'Air Compressor Hose',
  'Jack Handle',
  'Tow Rope',
  'Jump Cable Set',
  'Engine Gasket Set',
  'Cylinder Head Gasket',
  'Valve Cover Gasket',
  'Sump Gasket',
  'Oil Seal Front',
  'Oil Seal Rear',
  'Piston Ring Set',
  'Main Bearing Set',
  'Big End Bearing Set',
  'Valve Stem Seal Set',
  'Turbo Charger',
  'Intercooler Hose',
  'Exhaust Mount',
  'Exhaust Gasket',
  'Silencer Box',
  'Catalytic Converter',
  'Muffler Clamp',
  'Number Plate Bolt',
  'Workshop Degreaser',
  'Brake Cleaner',
  'Carb Cleaner',
  'Injector Cleaner',
  'Hand Cleaner Soap',
  'Rags Bundle',
  'Zip Tie Pack',
  'Hose Clamp Small',
  'Hose Clamp Medium',
  'Hose Clamp Large',
  'Copper Washer Set',
  'O-Ring Assortment',
  'Drain Plug Washer',
  'Engine Flush',
  'Radiator Flush',
  'Tyre Shine',
  'Car Shampoo',
  'Polish Compound',
  'Body Filler',
  'Primer Spray',
  'Touch Up Paint',
  'Sandpaper Pack',
  'Masking Tape',
  'Workshop Gloves',
  'Safety Glasses',
] as const